openapi: 3.0.0
info:
  title: "Shareholding pattern Service Project"
  contact:
    name: "Brijesh Bhomkar"
    url:  ""
    email: "Brijesh.Bhomkar@gmail.com"
  description: "Shareholding pattern service"
  version: "1.0.0"

paths:
  /get:





