servers:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://symboldbinstance.cnkio2je6qk2.us-east-2.rds.amazonaws.com:5432/symboldbinstance
    username: p0stgres
    password: postgres
    pool-size: 30