servers:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/symboldbinstance
    username: postgres
    password: p0stgres
    pool-size: 30